[package]
name = "rmatrix_ks"
authors = ["Kevin Stephen <qarks@icloud.com>"]
version = "0.3.7"
edition = "2021"
resolver = "2"
license = "AGPL-3.0-or-later"
description = "matrix and some algebra in Rust"
readme = "README.md"
repository = "https://github.com/kands-code/rmatrix"
documentation = "https://docs.rs/rmatrix_ks"

[package.metadata.doc.rs]
features = ["rand_mat", "rayon_mat", "serde_mat"]
all-features = true
no-default-features = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rmatrix_ks"
path = "src/lib.rs"
crate-type = ["staticlib", "rlib"]

[dependencies]
rayon = { version = "^1.10.0", optional = true }
rand = { version = "^0.8.5", optional = true }
serde = { version = "^1.0.204", features = ["derive"], optional = true }
serde_json = { version = "^1.0.122", optional = true }

[features]
default = ["rand_mat"]
rayon_mat = ["rayon"]
rand_mat = ["rand"]
serde_mat = ["serde", "serde_json"]

[dev-dependencies]
rand = "^0.8.5"
