[package]
name = "rmatrix_ks"
authors = ["Kevin Stephen <qarks@icloud.com>"]
version = "0.5.7"
resolver = "2"
edition = "2024"
rust-version = "1.88"
license = "AGPL-3.0-or-later"
description = "matrix and some algebra in Rust"
readme = "README.md"
keywords = ["math", "linear", "matrix", "number"]
repository = "https://github.com/kands-code/rmatrix"
documentation = "https://docs.rs/rmatrix_ks"

# default config for docs.rs
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "doc_cfg", "--generate-link-to-definition"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rmatrix_ks"
path = "src/lib.rs"
crate-type = ["rlib", "staticlib"]

[dependencies]
# for pattern validate
regex = "^1.11.1"
# for random matrix and random number
rand = "^0.9.0"
# for optimize
rayon = "^1.10.0"
