[package]
name = "rmatrix_ks"
authors = ["Kevin Stephen <qarks@icloud.com>"]
version = "0.4.2"
resolver = "2"
edition = "2021"
rust-version = "1.81"
license = "AGPL-3.0-or-later"
description = "matrix and some algebra in Rust"
readme = "README.md"
keywords = ["math", "matrix"]
repository = "https://github.com/kands-code/rmatrix"
documentation = "https://docs.rs/rmatrix_ks"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "doc_cfg", "--generate-link-to-definition"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rmatrix_ks"
path = "src/lib.rs"
crate-type = ["rlib"]

[dependencies]
# for pattern validate
regex = "^1.11.0"
# for random matrix and random number
rand = { version = "^0.8.5", optional = true }
# for data dump and restore
serde = { version = "^1.0.210", features = ["derive"], optional = true }
serde_json = { version = "^1.0.128", optional = true }

[features]
default = ["rand_mat"]
rand_mat = ["rand"]
serde_mat = ["serde", "serde_json"]
